#spring.application.name=emt-2025
#
#spring.datasource.url=jdbc:h2:mem:emt-2025
#spring.datasource.username=emt
#spring.datasource.password=emt
#
#spring.jpa.hibernate.ddl-auto=create-drop
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#
#spring.jpa.show-sql=false
#spring.thymeleaf.cache=false
#
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
####
#spring.application.name=emt-2025
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
#spring.datasource.username=user
#spring.datasource.password=password
#
#spring.jpa.hibernate.ddl-auto=none
#
#spring.jpa.show-sql=true
##spring.sql.init.mode=always
##spring.sql.init.schema-locations=classpath:init.sql
#
#spring.thymeleaf.cache=false
#
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=emt-2025

spring.datasource.url=jdbc:postgresql://localhost:5433/bookdb
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql
spring.jpa.hibernate.ddl-auto=none

jwt.secret=dGhpcy1pcy1hLXNlY3VyZS1qd3Qtc2VjcmV0LWZvci1lbXQtMjAyNQ==

